name: Java CI

on: [push]

jobs:
  buildJar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
          
      - name: Install Android Build Tools
        run: sudo apt-get update && sudo apt-get install -y android-sdk build-essential

      - name: Set up ANDROID_HOME and PATH
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$ANDROID_HOME/build-tools/30.0.1" >> $GITHUB_PATH

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Build mod jar
        run: ./gradlew deploy

      - name: Upload built jar file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: build/libs/${{ github.event.repository.name }}.jar
